name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.0"

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Build the Flutter web app
        run: |
          flutter build web

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'nehatanwardev'
          git config --global user.email 'nehatanwar.dev@gmail.com'

          # Create the gh-pages branch if it doesn't exist
          git checkout -b gh-pages

          # Copy the web build files to the root of the gh-pages branch
          cp -r build/web/* .

          # Add and commit the changes
          git add .
          git commit -m "Deploy Flutter web app to GitHub Pages"

          # Push changes to the gh-pages branch
          git push --force origin gh-pages
